version: '3.8'

services:
  backend:
    image: backend
    container_name: backend-temurin-21-jdk-alpine
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - trackero
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/trackero
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  frontend:
    image: frontend
    container_name: frontend-node-21-alpine3.19
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - trackero
    depends_on:
      - backend

  db:
    image: "postgres:12.17-alpine"
    container_name: db-postgres-12.17-alpine
    ports:
      - 5432:5432
    networks:
      - trackero
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trackero
    restart: always
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgres/data

volumes:
  postgres:

networks:
  trackero:
    driver: bridge